// Mocks generated by Mockito 5.4.0 from annotations
// in dart_kit/test/src/base_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'base_mocks.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CallbackVoid].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbackVoid extends _i1.Mock implements _i2.CallbackVoid {
  MockCallbackVoid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CallbackInt].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbackInt extends _i1.Mock implements _i2.CallbackInt {
  MockCallbackInt() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [CallbackString].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbackString extends _i1.Mock implements _i2.CallbackString {
  MockCallbackString() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: '',
      ) as String);
}

/// A class which mocks [ValueCallbackStringInt].
///
/// See the documentation for Mockito's code generation for more information.
class MockValueCallbackStringInt extends _i1.Mock
    implements _i2.ValueCallbackStringInt {
  MockValueCallbackStringInt() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call(String? param) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: 0,
      ) as int);
}
