name: dart_kit
description: Core Dart Kit Utils
version: 0.0.1
publish_to: none
# homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  logger: ^2.5.0
  meta: 1.15.0
  rxdart: 0.27.7

dev_dependencies:
  build_runner: 2.4.4
  lint: 1.10.0
  mockito: 5.4.0
  test: 1.24.2
  very_good_analysis: 3.0.1
